title: "Shreyas Bakare | High Energy Physics"
author: "Shreyas Bakare"
email: "your-email@example.com"
description: "Personal website of Shreyas Bakare, featuring research, publications, projects, and outreach in experimental high-energy physics."
baseurl: ""
url: "https://yourgithubusername.github.io"
github_username: "yourgithubusername"

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation Links
nav_links:
  Home: "/"
  Research: "/research"
  Publications: "/publications"
  Talks: "/talks"
  CV: "/cv"
  Contact: "/contact"

# Social Links
social:
  github: "https://github.com/yourgithubusername"
  linkedin: "https://linkedin.com/in/yourprofile"
  youtube: "https://youtube.com/yourchannel"
